version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack --mode=development

artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/*
    - images/*
    - dist/bundle.js